// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whffcrkspkkmmnbueflc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZmZjcmtzcGtrbW1uYnVlZmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0ODUyOTEsImV4cCI6MjA1NzA2MTI5MX0.vOycPj_siGJ9wKMUrdpmh4q3VjT96GNyspn2g0p9MM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);